name: currency_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  flutter_holo_date_picker: ^1.1.0
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.2.10
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  email_validator: ^2.1.17
  auto_route: ^7.8.3
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
        - asset: assets/fonts/jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jost/Jost-Bold.ttf
          weight: 700
